config/routes.rb
Rails.application.routes.draw do
  get 'travels/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'custom_sessions' }

  authenticate :user, ->(user) { user.superadmin? } do
    mount GoodJob::Engine => 'good_job'
    mount SystemSettings::Engine, at: '/system_settings'
  end

  mount Blazer::Engine, at: 'reports'

  resources :cars
  resources :dash_boards, only: [:index]
  resources :employees
  resources :insurance_plans
  resources :maintenances
  resources :organizations
  resources :repairs
  resources :suppliers
  resources :users do
    resources :notifications, only: %i[index show destroy]
  end
  resources :work_orders
  get 'search', to: 'search#index'
  get 'reports/work_orders'
  get 'searcher/search'
  resources :travels, only: %i[index update]

  # Defines the root path route ("/")
  root 'dash_boards#index'
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :bigint           not null, primary key
#  params          :jsonb
#  read_at         :datetime
#  recipient_type  :string           not null
#  type            :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :bigint
#  recipient_id    :bigint           not null
#
# Indexes
#
#  index_notifications_on_organization_id  (organization_id)
#  index_notifications_on_read_at          (read_at)
#  index_notifications_on_recipient        (recipient_type,recipient_id)
#
class Notification < ApplicationRecord
  # Constants
  # Enums
  # Associations (belongs_to, has_one, has_many, has_and_belongs_to_many)
  # Extensions (includes Rails concerns)
  # Scopes
  # Validations
  # Callbacks (before_save, after_commit, etc.)
  # Delegations
  # Virtual attributes (attr_accessor, etc.)
  # Class methods (self.method)
  # Instance methods
  # Private methods
  include Noticed::Model
  belongs_to :recipient, polymorphic: true

  multi_tenant :organization

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at updated_at]
  end
end

app/controllers/notifications_controller.rb
# Notification Controller
class NotificationsController < ApplicationController
  before_action :set_user, only: %i[index show destroy]
  before_action :set_notification, only: %i[show destroy]

  respond_to :html
  def index
    # Use for breadcrumbs_on_rails gem
    add_breadcrumb I18n.t('activerecord.models.notification.other'), user_notifications_url(only_path: true)
    @q = @user.notifications.ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @notifications = @q.result(distinct: true).page(params[:page]).per(25)

    respond_to do |format|
      format.html
      format.json do
        render json: {
          draw: '1',
          recordsTotal: @notifications.size,
          recordsFiltered: @notifications.size,
          data: @notifications.map { |notification| { message: 'hola', status: notification.read? } }
        }
      end
    end
  end

  def show
    # Use for breadcrumbs_on_rails gem
    add_breadcrumb I18n.t('activerecord.models.notification.other'), user_notifications_url(only_path: true)
    add_breadcrumb I18n.t('buttons.show'), nil
    @notification.mark_as_read!
    respond_with(@notification)
  end

  def destroy
    @notification.destroy
    respond_with(@user, @notification)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_notification
    @notification = @user.notifications.find(params[:id])
  end
end

app/views/notifications/_notification.html.erb
<div id="<%= dom_id notification %>">
</div>

app/views/notifications/index.html.erb
<%#= render 'search_form', ransack: @ransack %>

<div class="card">
  <h5 class="card-header">
    <%= t('activerecord.models.notification.other') %>
  </h5>

  <div class="table-responsive text-nowrap">
    <!--<div class="absolute z-30 w-full ml-10 pt-px" data-item-select-all-target="selectAllOverlay">
      <div class="bg-white flex items-center h-9 mt-0.5">
        <div class="mt-1.5" data-item-select-all-target="unselectedMessage">
          <span class="font-bold text-gray-700">48</span> records selected on this page from a total of <span class="font-bold text-gray-700">437</span>
          <a class="button-component inline-flex flex-grow-0 items-center font-semibold leading-6 fill-current whitespace-nowrap transition duration-100 transform transition duration-100 cursor-pointer disabled:cursor-not-allowed disabled:opacity-70 border justify-center active:outline active:outline-1 relative -top-[0.1rem] ml-2 cursor-pointer text-primary-500 rounded bg-white text-primary-500 border-primary-500 hover:bg-primary-100 active:bg-primary-100 active:border-primary-500 active:outline-primary-500 px-2 py-0 text-xs" data-action="click->item-select-all#selectAll" href="https://lcs-api-dev.le.mu/admin/resources/transactions?page=1&amp;per_page=48"><span>
            Select all matching</span>
          </a>
        </div>
        <div class="mt-1.5 hidden" data-item-select-all-target="selectedMessage">
          <span class="font-bold text-gray-700">437</span> records selected from all pages
          <a class="button-component inline-flex flex-grow-0 items-center font-semibold leading-6 fill-current whitespace-nowrap transition duration-100 transform transition duration-100 cursor-pointer disabled:cursor-not-allowed disabled:opacity-70 border justify-center active:outline active:outline-1 relative -top-[0.1rem] ml-2 cursor-pointer text-primary-500 rounded bg-white text-primary-500 border-primary-500 hover:bg-primary-100 active:bg-primary-100 active:border-primary-500 active:outline-primary-500 px-2 py-0 text-xs" data-action="click->item-select-all#selectAll" href="https://lcs-api-dev.le.mu/admin/resources/transactions?page=1&amp;per_page=48"><span>
            Undo
          </span>
          </a>
        </div>
      </div>
    </div>-->
    <table class="table">
      <caption class="ms-4">
        <div class="d-flex align-items-center justify-content-between">
          <div class="mr-auto">
            <%= page_entries_info @notifications, entry_name: 'item' %>
          </div>
          <%= paginate @notifications, remote: true %>
        </div>
      </caption>
      <thead>
      <tr>
        <th><input type="checkbox" id="select-all" /></th>
        <th>
          <%= t('activerecord.attributes.notification.message') %>
        </th>
        <th>
          <%= t('activerecord.attributes.notification.status') %>
        </th>
      </tr>
      </thead>
      <tbody>
      <% @notifications.each do |notification| %>
        <tr>
          <td><%= check_box_tag 'item_ids[]', notification.id, false, class: 'item-checkbox' %></td>
          <td><strong><%= link_to notification.params[:message], user_notification_path(@user, notification) %></strong></td>
          <td><%= content_tag(:span, "Sin leer", class: 'badge bg-label bg-primary') if notification.unread? %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/notifications/show.html.erb
<div class="card mb-4">
  <h5 class="card-header">
    <%= t("activerecord.models.notification.one") + " ##{@notification.id}" %>
  </h5>
  <div class="card-body">
    <div class="row">
      <div class="col-xl-12">
        <p>
          <%= @notification.params[:message] %>
        </p>
      </div>
    </div>
  </div>
</div>