config/routes.rb
Rails.application.routes.draw do
  get 'travels/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'custom_sessions' }

  authenticate :user, ->(user) { user.superadmin? } do
    mount GoodJob::Engine => 'good_job'
    mount SystemSettings::Engine, at: '/system_settings'
  end

  mount Blazer::Engine, at: 'reports'

  resources :cars
  resources :dash_boards, only: [:index]
  resources :employees
  resources :insurance_plans
  resources :maintenances
  resources :organizations
  resources :repairs
  resources :suppliers
  resources :users do
    resources :notifications, only: %i[index show destroy]
  end
  resources :work_orders
  get 'search', to: 'search#index'
  get 'reports/work_orders'
  get 'searcher/search'
  resources :travels, only: %i[index update]

  # Defines the root path route ("/")
  root 'dash_boards#index'
end

app/controllers/blazer/queries_controller.rb
module Blazer
  class QueriesController < BaseController
    before_action :set_query, only: [:show, :edit, :update, :destroy, :refresh]
    before_action :set_data_source, only: [:tables, :docs, :schema, :cancel]
    skip_before_action :verify_authenticity_token


    def home
      set_queries(1000)

      if params[:filter]
        @dashboards = [] # TODO show my dashboards
      else
        @dashboards = Blazer::Dashboard.order(:name)
        @dashboards = @dashboards.includes(:creator) if Blazer.user_class
      end

      @dashboards =
        @dashboards.map do |d|
          {
            id: d.id,
            name: d.name,
            creator: blazer_user && d.try(:creator) == blazer_user ? "You" : d.try(:creator).try(Blazer.user_name),
            to_param: d.to_param,
            dashboard: true
          }
        end
    end

    def index
      set_queries
      render json: @queries
    end

    def new
      @query = Blazer::Query.new(
        data_source: params[:data_source],
        name: params[:name]
      )
      if params[:fork_query_id]
        @query.statement ||= Blazer::Query.find(params[:fork_query_id]).try(:statement)
      end
      if params[:upload_id]
        upload = Blazer::Upload.find(params[:upload_id])
        upload_settings = Blazer.settings["uploads"]
        @query.data_source ||= upload_settings["data_source"]
        @query.statement ||= "SELECT * FROM #{upload.table_name} LIMIT 10"
      end
    end

    def create
      @query = Blazer::Query.new(query_params)
      @query.creator = blazer_user if @query.respond_to?(:creator)
      @query.status = "active" if @query.respond_to?(:status)

      if @query.save
        redirect_to query_path(@query, params: variable_params(@query))
      else
        render_errors @query
      end
    end

    def show
      @statement = @query.statement_object
      @success = process_vars(@statement)

      @smart_vars = {}
      @sql_errors = []
      @bind_vars.each do |var|
        smart_var, error = parse_smart_variables(var, @statement.data_source)
        @smart_vars[var] = smart_var if smart_var
        @sql_errors << error if error
      end

      @query.update!(status: "active") if @query.respond_to?(:status) && @query.status.in?(["archived", nil])

      add_cohort_analysis_vars if @query.cohort_analysis?
    end

    def edit
    end

    def run
      @query = Query.find_by(id: params[:query_id]) if params[:query_id]

      # use query data source when present
      # need to update viewable? logic below if this changes
      data_source = @query.data_source if @query && @query.data_source
      data_source ||= params[:data_source]
      @data_source = Blazer.data_sources[data_source]

      @statement = Blazer::Statement.new(params[:statement], @data_source)
      # before process_vars
      @cohort_analysis = @statement.cohort_analysis?

      # fallback for now for users with open tabs
      # TODO remove fallback in future version
      @var_params = request.request_parameters["variables"] || request.request_parameters
      @success = process_vars(@statement, @var_params)
      @only_chart = params[:only_chart]
      @run_id = blazer_params[:run_id]

      run_cohort_analysis if @cohort_analysis

      # ensure viewable
      if !(@query || Query.new(data_source: @data_source.id)).viewable?(blazer_user)
        render_forbidden
      elsif @run_id
        @timestamp = blazer_params[:timestamp].to_i

        @result = @data_source.run_results(@run_id)
        @success = !@result.nil?

        if @success
          @data_source.delete_results(@run_id)
          @columns = @result.columns
          @rows = @result.rows
          @error = @result.error
          @just_cached = !@result.error && @result.cached_at.present?
          @cached_at = nil
          params[:data_source] = nil
          render_run
        elsif Time.now > Time.at(@timestamp + (@data_source.timeout || 600).to_i + 5)
          # query lost
          Rails.logger.info "[blazer lost query] #{@run_id}"
          @error = "We lost your query :("
          @rows = []
          @columns = []
          render_run
        else
          continue_run
        end
      elsif @success
        @run_id = blazer_run_id

        options = {user: blazer_user, query: @query, refresh_cache: params[:check], run_id: @run_id, async: Blazer.async}
        if Blazer.async && request.format.symbol != :csv
          Blazer::RunStatementJob.perform_later(@data_source.id, @statement.statement, options.merge(values: @statement.values))
          wait_start = Blazer.monotonic_time
          loop do
            sleep(0.1)
            @result = @data_source.run_results(@run_id)
            break if @result || Blazer.monotonic_time - wait_start > 3
          end
        else
          @result = Blazer::RunStatement.new.perform(@statement, options)
        end

        if @result
          @data_source.delete_results(@run_id) if @run_id

          @columns = @result.columns
          @rows = @result.rows
          @error = @result.error
          @cached_at = @result.cached_at
          @just_cached = @result.just_cached

          @forecast = @query && @result.forecastable? && params[:forecast]
          if @forecast
            @result.forecast
            @forecast_error = @result.forecast_error
            @forecast = @forecast_error.nil?
          end

          render_run
        else
          @timestamp = Time.now.to_i
          continue_run
        end
      else
        render layout: false
      end
    end

    def refresh
      refresh_query(@query)
      redirect_to query_path(@query, params: variable_params(@query))
    end

    def update
      if params[:commit] == "Fork"
        @query = Blazer::Query.new
        @query.creator = blazer_user if @query.respond_to?(:creator)
      end
      @query.status = "active" if @query.respond_to?(:status)
      unless @query.editable?(blazer_user)
        @query.errors.add(:base, "Sorry, permission denied")
      end
      if @query.errors.empty? && @query.update(query_params)
        redirect_to query_path(@query, params: variable_params(@query))
      else
        render_errors @query
      end
    end

    def destroy
      @query.destroy if @query.editable?(blazer_user)
      redirect_to root_path
    end

    def tables
      render json: @data_source.tables
    end

    def docs
      @smart_variables = @data_source.smart_variables
      @linked_columns = @data_source.linked_columns
      @smart_columns = @data_source.smart_columns
    end

    def schema
      @schema = @data_source.schema
    end

    def cancel
      @data_source.cancel(blazer_run_id)
      head :ok
    end

    private

      def set_data_source
        @data_source = Blazer.data_sources[params[:data_source]]

        unless Query.new(data_source: @data_source.id).editable?(blazer_user)
          render_forbidden
        end
      end

      def continue_run
        render json: {run_id: @run_id, timestamp: @timestamp}, status: :accepted
      end

      def render_run
        @checks = @query ? @query.checks.order(:id) : []

        @first_row = @rows.first || []
        @column_types = []
        if @rows.any?
          @columns.each_with_index do |_, i|
            @column_types << (
              case @first_row[i]
              when Integer
                "int"
              when Float, BigDecimal
                "float"
              else
                "string-ins"
              end
            )
          end
        end

        @min_width_types = @columns.each_with_index.select { |c, i| @first_row[i].is_a?(Time) || @first_row[i].is_a?(String) || @data_source.smart_columns[c] }.map(&:last)

        @boom = @result.boom if @result

        @linked_columns = @data_source.linked_columns

        @markers = []
        [["latitude", "longitude"], ["lat", "lon"], ["lat", "lng"]].each do |keys|
          lat_index = @columns.index(keys.first)
          lon_index = @columns.index(keys.last)
          if lat_index && lon_index
            @markers =
              @rows.select do |r|
                r[lat_index] && r[lon_index]
              end.map do |r|
                {
                  # Mapbox.js does sanitization with https://github.com/mapbox/sanitize-caja
                  # but we should do it here as well
                  title: r.each_with_index.map { |v, i| i == lat_index || i == lon_index ? nil : "<strong>#{ERB::Util.html_escape(@columns[i])}:</strong> #{ERB::Util.html_escape(v)}" }.compact.join("<br />").truncate(140),
                  latitude: r[lat_index],
                  longitude: r[lon_index]
                }
              end
          end
        end

        render_cohort_analysis if @cohort_analysis && !@error

        respond_to do |format|
          format.html do
            render layout: false
          end
          format.csv do
            # not ideal, but useful for testing
            raise Error, @error if @error && Rails.env.test?

            send_data csv_data(@columns, @rows, @data_source), type: "text/csv; charset=utf-8; header=present", disposition: "attachment; filename=\"#{@query.try(:name).try(:parameterize).presence || 'query'}.csv\""
          end
        end
      end

      def set_queries(limit = nil)
        @queries = Blazer::Query.named.select(:id, :name, :creator_id, :statement)
        @queries = @queries.includes(:creator) if Blazer.user_class

        if blazer_user && params[:filter] == "mine"
          @queries = @queries.where(creator_id: blazer_user.id).reorder(updated_at: :desc)
        elsif blazer_user && params[:filter] == "viewed" && Blazer.audit
          @queries = queries_by_ids(Blazer::Audit.where(user_id: blazer_user.id).order(created_at: :desc).limit(500).pluck(:query_id).uniq)
        else
          @queries = @queries.limit(limit) if limit
          @queries = @queries.active.order(:name)
        end
        @queries = @queries.to_a

app/views/layouts/blazer/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if @query && @query.name %>
        <%= "#{@query.name.downcase.gsub(' ', '_')}_#{l(DateTime.now)}" %>
      <% else %>
        <%= SystemSettings[:site_name] %>
      <% end %>
    </title>
    <%= favicon_link_tag asset_path(SystemSettings[:favicon]) %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <%#= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", type: "module", defer: true %>

    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    <%= favicon_link_tag "blazer/favicon.png" %>
    <% if defined?(Propshaft::Railtie) %>
      <%= stylesheet_link_tag "blazer/bootstrap-propshaft", "blazer/bootstrap", "blazer/selectize", "blazer/github", "blazer/daterangepicker", "blazer/application" %>
      <%= javascript_include_tag "blazer/jquery", "blazer/jquery-ujs", "blazer/stupidtable", "blazer/stupidtable-custom-settings", "blazer/jquery.stickytableheaders", "blazer/selectize", "blazer/highlight.min", "blazer/moment", "blazer/moment-timezone-with-data", "blazer/daterangepicker", "blazer/Chart.js", "blazer/chartkick", "blazer/ace/ace", "blazer/ace/ext-language_tools", "blazer/ace/theme-twilight", "blazer/ace/mode-sql", "blazer/ace/snippets/text", "blazer/ace/snippets/sql", "blazer/Sortable", "blazer/bootstrap", "blazer/vue", "blazer/routes", "blazer/queries", "blazer/fuzzysearch", "blazer/application" %>
    <% else %>
      <%= stylesheet_link_tag "blazer/application" %>
      <%= javascript_include_tag "blazer/application" %>
    <% end %>
    <script>
      <%= blazer_js_var "rootPath", root_path %>
    </script>
    <% if blazer_maps? %>
      <%= stylesheet_link_tag "https://api.mapbox.com/mapbox.js/v3.3.1/mapbox.css", integrity: "sha384-vxzdEt+wZRPNQbhChjmiaFMLWg86IGuq1NGDehJHsD2mphYkxXll/eSs16WWi6Dq", crossorigin: "anonymous" %>
      <%= javascript_include_tag "https://api.mapbox.com/mapbox.js/v3.3.1/mapbox.js", integrity: "sha384-CTBEiDLiZJ8gkAQ3fYGoeiRp81/ecNiBkGz11jXFALOZ6++rbnqmdo6OImkmr1MO", crossorigin: "anonymous" %>
    <% end %>
  </head>
  <body>

      <!-- Layout wrapper -->
      <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
          <!-- Menu -->
          <%= render(partial: 'layouts/sidebar') %>
          <!-- / Menu -->

          <!-- Layout container -->
          <div class="layout-page">
            <div id="flash">
              <% flash.each do |role, message| %>
                <%= render(partial: 'shared/flash', locals: { role: role, message: message }) %>
              <% end %>
            </div>

            <nav class="layout-navbar container-fluid navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme " id="layout-navbar">
              <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#ok">
                  <span class="navbar-toggler-icon"></span>
                </button>
              </div>
              <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                <!-- Search -->
                <%= render(SearchComponent.new) %>
                <!--/ Search -->
                <ul class="navbar-nav flex-row align-items-center ms-auto">
                  <!-- Notification -->
                  <%#= render(NotificationComponent.new(notifications: @current_user.notifications,
                                                       link_to_all_notification: user_notifications_path(@current_user))) %>
                  <!--/ Notification -->

                  <!-- User -->
                  <li class="nav-item navbar-dropdown dropdown-user dropdown">
                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                      <div class="avatar avatar-online">
                        <%= image_tag(@current_user.avatar.variant(resize: "100x100") || "user-avatar.svg",
                                      size: '100',
                                      alt: 'Profile image',
                                      class: 'w-px-40 h-auto rounded-circle')
                        %>
                      </div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                      <li>
                        <a class="dropdown-item" href="#">
                          <div class="d-flex">
                            <div class="flex-shrink-0 me-3">
                              <div class="avatar avatar-online">
                                <%= image_tag(@current_user.avatar.variant(resize: "100x100") || "user-avatar.svg",
                                              size: '100',
                                              alt: 'Profile image',
                                              class: 'w-px-40 h-auto rounded-circle')
                                %>
                              </div>
                            </div>
                            <div class="flex-grow-1">
                              <span class="fw-semibold d-block"><%= @current_user.email %></span>
                              <small class="text-muted">Admin</small>
                            </div>
                          </div>
                        </a>
                      </li>
                      <li>
                        <div class="dropdown-divider"></div>
                      </li>
                      <li>
                        <a class="dropdown-item" href="<%#= edit_user_path(@current_user) %>">
                          <i class="bx bx-user me-2"></i>
                          <span class="align-middle"><%= t('profile') %></span>
                        </a>
                      </li>
                      <li>
                        <div class="dropdown-divider"></div>
                      </li>
                      <li>
                        <%#= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
<!--                          <i class="bx bx-power-off me-2"></i>-->
<!--                          <span class="align-middle"><%#= t('logout') %></span>-->
                        <%# end %>
                      </li>
                    </ul>
                  </li>
                  <!--/ User -->


                </ul>
              </div>
            </nav>

            <!-- Content wrapper -->
            <div class="content-wrapper">

              <!-- Content -->
              <div class="container-fluid flex-grow-1 container-p-y">

                <h3 class="breadcrumbs">
                  <%#= render_breadcrumbs separator: ' / ' %>
                </h3>


                <!-- Layout Demo -->
                <%= yield %>

                <!--/ Layout Demo -->
              </div>
              <!-- / Content -->

              <!-- Footer -->
              <footer class="content-footer footer bg-footer-theme">
                <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                  <div class="mb-2 mb-md-0">
                    © Desarrollado por
                    <a href="https://github.com/afaraldo" class="footer-link fw-bolder">@afaraldo</a> y
                    <a href="https://github.com/KariSanabria" class="footer-link fw-bolder">KariSanabria</a>
                    <%= APP_VERSION.to_s %>
                  </div>
                </div>
              </footer>
              <!-- / Footer -->
              <div class="content-backdrop fade"></div>
            </div>
            <!-- Content wrapper -->
          </div>
          <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <!--<div class="layout-overlay layout-menu-toggle"></div>-->
      </div>
      <!-- / Layout wrapper -->


  </body>
</html>